export const mockProducts = [
  {
    id: 1,
    name: 'Luxury Rose Oud Perfume',
    nameAr: 'عطر عود الورد الفاخر',
    price: '450 SAR',
    category: 'Perfumes',
    image: '🌹',
    description: 'Premium blend of rose and oud',
  },
  {
    id: 2,
    name: 'Signature Musk Collection',
    nameAr: 'مجموعة المسك المميزة',
    price: '320 SAR',
    category: 'Perfumes',
    image: '💎',
    description: 'Signature musk fragrance',
  },
  {
    id: 3,
    name: 'Amber Gold Body Oil',
    nameAr: 'زيت العنبر الذهبي',
    price: '180 SAR',
    category: 'Body Care',
    image: '✨',
    description: 'Luxurious body oil with amber',
  },
  {
    id: 4,
    name: 'Bakhoor Deluxe',
    nameAr: 'بخور فاخر',
    price: '220 SAR',
    category: 'Home Fragrance',
    image: '🔥',
    description: 'Premium bakhoor for special occasions',
  },
];

export const mockContentIdeas = [
  {
    id: 1,
    type: 'Instagram Post',
    typeAr: 'منشور انستقرام',
    title: 'The Story Behind Our Rose Oud',
    titleAr: 'قصة عطر الورد والعود',
    content: 'Every drop of our Luxury Rose Oud carries centuries of tradition. Discover the artistry behind our signature scent that has captured hearts across the Kingdom.',
    contentAr: 'كل قطرة من عطر الورد والعود الفاخر تحمل قروناً من التقاليد. اكتشف الفن وراء العطر المميز الذي أسر القلوب في المملكة.',
    hashtags: ['#RoseOud', '#SaudiPerfumes', '#LuxuryFragrance', '#عطور_فاخرة'],
    engagementScore: 92,
    predictedReach: '12.5K',
    suggestedTime: 'Tomorrow, 8:00 PM',
    status: 'pending',
    image: '🌹',
  },
  {
    id: 2,
    type: 'Instagram Reel',
    typeAr: 'ريل انستقرام',
    title: 'How to Layer Fragrances Like a Pro',
    titleAr: 'كيف تنسق العطور كالمحترفين',
    content: '3 pro tips for layering your favorite fragrances to create a signature scent that\'s uniquely you. Perfect for special evenings.',
    contentAr: '3 نصائح احترافية لتنسيق عطورك المفضلة وإنشاء توقيع عطري خاص بك. مثالي للأمسيات الخاصة.',
    hashtags: ['#FragranceLayering', '#PerfumeTips', '#عطور'],
    engagementScore: 88,
    predictedReach: '18.2K',
    suggestedTime: 'Thursday, 9:30 PM',
    status: 'pending',
    image: '💫',
  },
  {
    id: 3,
    type: 'Story Series',
    typeAr: 'سلسلة قصص',
    title: 'Behind the Scenes: Perfume Making',
    titleAr: 'كواليس صناعة العطور',
    content: 'Take a journey through our atelier. From selecting the finest oud to blending each unique fragrance, see the craft that makes our perfumes special.',
    contentAr: 'خذ جولة في معملنا. من اختيار أجود أنواع العود إلى مزج كل عطر فريد، شاهد الحرفية التي تجعل عطورنا مميزة.',
    hashtags: ['#BehindTheScenes', '#PerfumeCraft', '#كواليس'],
    engagementScore: 85,
    predictedReach: '9.8K',
    suggestedTime: 'Saturday, 11:00 AM',
    status: 'approved',
    image: '🎨',
  },
  {
    id: 4,
    type: 'Twitter Post',
    typeAr: 'تغريدة',
    title: 'Ramadan Special Collection',
    titleAr: 'مجموعة رمضان الخاصة',
    content: 'Our exclusive Ramadan collection is here. Featuring rich bakhoor, delicate ouds, and gift-ready packaging. Perfect for the blessed month.',
    contentAr: 'مجموعة رمضان الحصرية هنا. بخور فاخر، عود مميز، وتغليف جاهز للإهداء. مثالي للشهر المبارك.',
    hashtags: ['#Ramadan2026', '#SaudiLuxury', '#رمضان'],
    engagementScore: 94,
    predictedReach: '25.4K',
    suggestedTime: 'Monday, 6:00 PM',
    status: 'pending',
    image: '🌙',
  },
  {
    id: 5,
    type: 'Instagram Carousel',
    typeAr: 'كاروسيل انستقرام',
    title: 'Customer Reviews: What Our Clients Say',
    titleAr: 'آراء العملاء: ماذا يقولون عنا',
    content: 'Real reviews from real customers. See why over 1,500 clients across Saudi Arabia trust us for their signature fragrances.',
    contentAr: 'آراء حقيقية من عملاء حقيقيين. شاهد لماذا يثق بنا أكثر من 1,500 عميل حول المملكة لاختيار عطورهم المميزة.',
    hashtags: ['#CustomerReviews', '#Trusted', '#آراء_العملاء'],
    engagementScore: 79,
    predictedReach: '7.3K',
    suggestedTime: 'Wednesday, 3:00 PM',
    status: 'pending',
    image: '⭐',
  },
  {
    id: 6,
    type: 'TikTok Video',
    typeAr: 'فيديو تيك توك',
    title: 'Fragrance Trends in 2026',
    titleAr: 'اتجاهات العطور في 2026',
    content: 'What\'s trending in the fragrance world right now? From sustainable sourcing to bold new blends, here\'s what\'s hot.',
    contentAr: 'ما هو الرائج في عالم العطور الآن؟ من المصادر المستدامة إلى المزجات الجريئة، هذا ما هو رائج.',
    hashtags: ['#FragranceTrends', '#2026Trends', '#عطور_2026'],
    engagementScore: 91,
    predictedReach: '32.1K',
    suggestedTime: 'Friday, 7:00 PM',
    status: 'pending',
    image: '🔥',
  },
];

export const mockFAQs = [
  {
    question: 'How long does the fragrance last?',
    questionAr: 'كم تدوم رائحة العطر؟',
    frequency: 47,
    suggestedContent: 'Create content about fragrance longevity tips',
  },
  {
    question: 'Do you ship internationally?',
    questionAr: 'هل تشحنون دولياً؟',
    frequency: 38,
    suggestedContent: 'Announcement post about international shipping',
  },
  {
    question: 'What\'s the difference between oud and musk?',
    questionAr: 'ما الفرق بين العود والمسك؟',
    frequency: 32,
    suggestedContent: 'Educational carousel comparing oud vs musk',
  },
  {
    question: 'Can I return unopened products?',
    questionAr: 'هل يمكن إرجاع المنتجات غير المفتوحة؟',
    frequency: 24,
    suggestedContent: 'Clear return policy story',
  },
  {
    question: 'Which perfume is best for winter?',
    questionAr: 'أي عطر مناسب لفصل الشتاء؟',
    frequency: 22,
    suggestedContent: 'Seasonal winter perfume guide',
  },
];

export const mockViralPosts = [
  {
    id: 1,
    platform: 'Instagram',
    type: 'Reel',
    thumbnail: '🎬',
    engagement: '156K',
    likes: '24.5K',
    comments: '1.8K',
    shares: '3.2K',
    topic: 'Perfume unboxing with signature reveal',
    insights: 'Users respond strongly to unboxing content with product reveals in the last 3 seconds.',
  },
  {
    id: 2,
    platform: 'TikTok',
    type: 'Tutorial',
    thumbnail: '📚',
    engagement: '98K',
    likes: '18.2K',
    comments: '947',
    shares: '2.1K',
    topic: 'How to test fragrances properly',
    insights: 'Educational content performs 3x better than promotional posts.',
  },
  {
    id: 3,
    platform: 'Instagram',
    type: 'Story',
    thumbnail: '⭐',
    engagement: '87K',
    likes: '14.7K',
    comments: '623',
    shares: '890',
    topic: 'Behind the scenes at the perfume atelier',
    insights: 'BTS content drives 40% higher save rate than product shots.',
  },
  {
    id: 4,
    platform: 'Twitter',
    type: 'Thread',
    thumbnail: '📝',
    engagement: '45K',
    likes: '8.4K',
    comments: '412',
    shares: '1.9K',
    topic: 'The history of oud in Arabian culture',
    insights: 'Cultural storytelling threads get shared 5x more than product tweets.',
  },
];

export const mockScheduledPosts = [
  { date: '2026-07-18', time: '09:00', platform: 'Instagram', title: 'Morning inspiration', status: 'scheduled' },
  { date: '2026-07-18', time: '18:00', platform: 'Twitter', title: 'Product highlight', status: 'scheduled' },
  { date: '2026-07-19', time: '11:00', platform: 'TikTok', title: 'Behind the scenes reel', status: 'scheduled' },
  { date: '2026-07-19', time: '20:00', platform: 'Instagram', title: 'Customer testimonial', status: 'draft' },
  { date: '2026-07-20', time: '08:00', platform: 'Instagram', title: 'Morning motivation', status: 'scheduled' },
  { date: '2026-07-20', time: '15:00', platform: 'Twitter', title: 'Tip of the day', status: 'scheduled' },
  { date: '2026-07-21', time: '10:00', platform: 'TikTok', title: 'Tutorial video', status: 'draft' },
  { date: '2026-07-22', time: '19:00', platform: 'Instagram', title: 'New collection reveal', status: 'scheduled' },
];

export const mockStats = {
  totalPosts: 147,
  scheduledPosts: 23,
  engagementRate: 8.4,
  audienceGrowth: 12.7,
  contentIdeasGenerated: 89,
  approvedContent: 34,
  weeklyReach: '156K',
  weeklyImpressions: '384K',
};

export const mockPlatforms = [
  { name: 'Instagram', icon: '📷', color: 'from-pink-500 to-purple-500', posts: 87, growth: '+12%' },
  { name: 'TikTok', icon: '🎵', color: 'from-black to-pink-500', posts: 42, growth: '+28%' },
  { name: 'Twitter', icon: '🐦', color: 'from-sky-400 to-blue-500', posts: 65, growth: '+8%' },
  { name: 'Snapchat', icon: '👻', color: 'from-yellow-400 to-yellow-500', posts: 34, growth: '+15%' },
];
